import os
import requests
from typing import Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()

def send_telegram_text(message: str, chat_id: Optional[str] = None) -> Dict[str, Any]:
    """
    Sends arbitrary markdown-formatted text to Telegram.
    """
    bot_token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    target_chat_id = (chat_id or os.getenv("TELEGRAM_CHAT_ID", "")).strip()

    if not bot_token or not target_chat_id:
        return {
            "status": False,
            "message": "Telegram not configured. Add TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to .env."
        }

    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": target_chat_id,
        "text": message,
        "parse_mode": "Markdown"
    }

    try:
        res = requests.post(url, json=payload, timeout=8)
        data = res.json()
        if data.get("ok"):
            return {"status": True, "message": "Message sent successfully"}
        return {"status": False, "message": f"Telegram API error: {data.get('description')}"}
    except Exception as e:
        return {"status": False, "message": f"Failed to send message: {str(e)}"}

def send_telegram_trade_alert(trade_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Sends a formatted trade alert to your phone via Telegram Bot API (Free).
    """
    symbol = trade_data.get("symbol", "STOCK")
    name = trade_data.get("name", symbol)
    verdict = trade_data.get("verdict", "HOLD")
    conviction = trade_data.get("conviction", 5)
    entry = trade_data.get("entry_range", "N/A")
    target = trade_data.get("target_price", "N/A")
    sl = trade_data.get("stop_loss", "N/A")
    rr = trade_data.get("risk_reward_ratio", "1:2")
    summary = trade_data.get("executive_summary", "")

    emoji = "🟢" if verdict == "BUY" else ("🔴" if verdict == "SELL" else "🟡")

    message = (
        f"{emoji} *TRADE ALERT: {verdict} {symbol}*\n"
        f"*{name}*\n\n"
        f"🎯 *Conviction:* {conviction} / 10\n"
        f"💵 *Entry Zone:* {entry}\n"
        f"🚀 *Target:* {target}\n"
        f"🛑 *Stop-Loss:* {sl}\n"
        f"⚖️ *Risk/Reward:* {rr}\n\n"
        f"📝 *Summary:* {summary}\n\n"
        f"_Generated by Bharat Trade Agent (NSE/BSE)_"
    )

    return send_telegram_text(message)
